year: "2021"
edition: "13th"
title: "Reversible Computation (RC)"
date: "July 7 - July 8, 2021"
place: "Nagoya, Japan"
tz:
  friendly: "Tokyo"
  iana: "asia/tokyo"
  offset: "UTC+09:00"
links:
  easychair: "https://easychair.org/conferences/?conf=rc2021"
images:
  local1: "/images/nagoya-cstl.jpg"
  local2: "/images/nu-esbldg.jpg"

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

exclude: ['vendor', 'README.md']